production:
  sessions:
    default:
      database: refriend_production
      hosts:
        - localhost:27017
      options:
        identity_map_enabled: true
  options:
    identity_map_enabled: true
    preload_models: true


development:
  sessions:
    default:
      database: refriend_development
      hosts:
        - localhost:27017
      options:
        identity_map_enabled: true
  options:
    identity_map_enabled: true
    preload_models: false

test:
  sessions:
    default:
      database: refriend_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
